import { MasterODS, FormatoEvento } from '../types/ods';

export function createBlankODS(customNumero?: string, customNome?: string, formato: FormatoEvento = 'buffet'): MasterODS {
  const odsNum = customNumero || `2026-${Math.floor(100 + Math.random() * 900)}`;
  const today = new Date().toLocaleDateString('it-IT');

  return {
    id: `ods-${Date.now()}`,
    scheda: {
      odsNumero: odsNum,
      revisioneCorrente: 'Rev. 0',
      dataRevisione: today,
      eventoNomeTipo: customNome || 'Nuovo Evento Catering',
      data: today,
      committente: 'Nome Committente / Azienda',
      luogoIndirizzo: 'Indirizzo Location Completo',
      inizioEvento: '20:00',
      fineEvento: '23:30',
      ingressoStaff: '16:30',
      partenzaBase: '15:00',
      ospitiAdulti: 100,
      ospitiBambiniSpeciali: 0,
      formato,
      redattoDa: 'Direttore / Capo Servizio',
      approvatoDa: 'Direzione Catering',
    },
    revisioni: [
      {
        rev: 'Rev. 0',
        data: today,
        cosaCambiato: 'Prima emissione ODS',
        autore: 'Direttore Catering',
      },
    ],
    moduliAttivi: {
      m1Guardaroba: false,
      m2Bambini: false,
      m3ProgrammaChef: false,
      m4TrasportoFurgone: true,
      m5CucinaRimpiazzi: true,
      m6DoppioTurno: false,
    },
    timelineFasi: [
      { codice: 'F1', nome: 'Carico materiale alla base', inizio: '14:00', fine: '15:00', cosaSuccede: 'Carico furgone, casse stoviglie e attrezzature', guidaResponsabile: 'Resp. Logistica', oraReale: '' },
      { codice: 'F2', nome: 'Partenza dalla base e arrivo in location', inizio: '15:00', fine: '16:15', cosaSuccede: 'Viaggio verso location e accesso scarico', guidaResponsabile: 'Autista', oraReale: '' },
      { codice: 'F3', nome: 'Ingresso staff e allestimento postazioni', inizio: '16:30', fine: '18:45', cosaSuccede: 'Montaggio buffet, buvette e mise en place', guidaResponsabile: 'Capo Servizio', oraReale: '' },
      { codice: 'F4', nome: 'Briefing finale della brigata', inizio: '18:45', fine: '19:15', cosaSuccede: 'Verifica postazioni, allergeni e standard di servizio', guidaResponsabile: 'Capo Servizio', oraReale: '' },
      { codice: 'F5', nome: 'Apertura e accoglienza ospiti', inizio: '19:30', fine: '20:30', cosaSuccede: 'Welcome drink e accoglienza al passaggio', guidaResponsabile: 'Capo Servizio', oraReale: '' },
      { codice: 'F6', nome: 'Servizio (aperitivo / pasto / programma)', inizio: '20:30', fine: '22:30', cosaSuccede: 'Servizio portate principali e rimpiazzi continui', guidaResponsabile: 'Capo Servizio', oraReale: '' },
      { codice: 'F7', nome: 'Sbarazzo e pulizia', inizio: '22:30', fine: '23:30', cosaSuccede: 'Ritiro bicchieri, differenziata e pulizia sale', guidaResponsabile: 'Resp. Sala', oraReale: '' },
      { codice: 'F8', nome: 'Chiusura, conteggi e carico di ritorno', inizio: '23:30', fine: '00:45', cosaSuccede: 'Conteggio bottiglie rimaste, verifica casse e carico', guidaResponsabile: 'Resp. Logistica', oraReale: '' },
      { codice: 'F9', nome: 'Rientro e scarico alla base', inizio: '00:45', fine: '01:45', cosaSuccede: 'Scarico magazzino e deposito stoviglie', guidaResponsabile: 'Resp. Logistica', oraReale: '' },
    ],
    contatti: [
      { id: 'c1', ruolo: 'Committente / referente cliente', nome: 'Referente Cliente', telefono: '+39 ', note: 'Presente in location' },
      { id: 'c2', ruolo: 'Referente in loco (location)', nome: 'Custode / Direzione Location', telefono: '+39 ', note: 'Chiavi e allacci' },
      { id: 'c3', ruolo: 'Capo servizio', nome: 'Nome Capo Servizio', telefono: '+39 ', note: 'Coordinamento generale' },
      { id: 'c4', ruolo: 'Responsabile carico e logistica', nome: 'Resp. Magazzino/Carico', telefono: '+39 ', note: 'Gestione furgone' },
      { id: 'c5', ruolo: 'Chef responsabile cucina (M5)', nome: 'Chef Esecutivo', telefono: '+39 ', note: 'Rigenerazione e linea piatti' },
    ],
    locationAccessi: {
      ingressoStaffPuntoRitrovo: 'Ingresso di servizio location',
      caricoScaricoPuntoFascia: 'Piazzale posteriore - fascia oraria 15:00 - 16:30',
      parcheggioMezzo: 'Area dedicata all’interno della proprietà',
      ztlPermessiAccesso: 'Verificare permessi di transito e varchi ZTL',
      percorsoInterno: 'Piano terra senza gradini / ascensore montacarichi',
      cucinaDisponibile: true,
      cucinaAttrezzature: 'Forni, frigoriferi e piani inox disponibili',
      acquaScarichi: 'Lavelli con acqua calda e pozzetto di scarico collegati',
      correntePresePotenza: 'Quadro 380V 32A + linee 220V 16A',
      spaziBackGuardarobaDeposito: 'Stanza office riservata al catering',
      serviziIgieniciSpogliatoio: 'Bagno staff dedicato',
      raccoltaRifiuti: 'Differenziata sul posto con asporto a fine servizio',
      sopralluogoFatto: true,
      sopralluogoData: today,
      sopralluogoDaChi: 'Capo Servizio',
      layoutPostazioniAllegato: true,
      layoutNote: 'Planimetria con segnate P1..P6',
    },
    divise: {
      staff: 'Pantaloni neri, camicia bianca collo francese, grembiule nero bistro, scarpe nere antiscivolo',
      capoServizioResponsabili: 'Abito scuro elegante, camicia bianca, cravatta istituzionale',
      cucina: 'Giacca chef bianca, grembiule nero, copricapo, zoccoli antinfortunistici',
      altro: 'Polo logata catering per facchinaggio e allestimento',
    },
    brigata: [
      { id: 'b1', n: 1, cognomeNome: 'Rossi Mario', ruolo: 'capo_servizio', ruoloDettaglio: 'Capo servizio', turno: '16:00 - 01:00', oreTotali: 9, stato: 'C', cellulare: '+39 340 0000001' },
      { id: 'b2', n: 2, cognomeNome: 'Bianchi Luigi', ruolo: 'responsabile', ruoloDettaglio: 'Barman & Buvette', turno: '16:30 - 00:30', oreTotali: 8, stato: 'C', cellulare: '+39 340 0000002' },
      { id: 'b3', n: 3, cognomeNome: 'Verdi Anna', ruolo: 'responsabile', ruoloDettaglio: 'Resp. Sala & Buffet', turno: '16:30 - 00:30', oreTotali: 8, stato: 'C', cellulare: '+39 340 0000003' },
      { id: 'b4', n: 4, cognomeNome: 'Ferrari Marco', ruolo: 'addetto', ruoloDettaglio: 'Cameriere / Runner', turno: '17:00 - 00:30', oreTotali: 7.5, stato: 'C', cellulare: '+39 340 0000004' },
      { id: 'b5', n: 5, cognomeNome: 'Esposito Sara', ruolo: 'addetto', ruoloDettaglio: 'Cameriere / Runner', turno: '17:00 - 00:30', oreTotali: 7.5, stato: 'C', cellulare: '+39 340 0000005' },
      { id: 'b6', n: 6, cognomeNome: 'Romano Davide', ruolo: 'addetto', ruoloDettaglio: 'Sbarazzo e back', turno: '17:00 - 01:00', oreTotali: 8, stato: 'C', cellulare: '+39 340 0000006' },
      { id: 'b7', n: 7, cognomeNome: 'Colombo Luca', ruolo: 'responsabile', ruoloDettaglio: 'Resp. Logistica & Carico', turno: '14:00 - 01:30', oreTotali: 11.5, stato: 'C', cellulare: '+39 340 0000007' },
      { id: 'b8', n: 8, cognomeNome: 'Ricci Paola', ruolo: 'responsabile', ruoloDettaglio: 'Chef Cucina M5', turno: '15:30 - 23:30', oreTotali: 8, stato: 'C', cellulare: '+39 340 0000008' },
    ],
    postazioni: [
      {
        codice: 'P1',
        nome: 'Accoglienza & Welcome',
        responsabileId: 'b1',
        attiva: true,
        faseA: { orario: '16:30 - 19:30 Allestimento desk', addettiIds: ['b1'] },
        faseB: { orario: '19:30 - 20:30 Welcome drink', addettiIds: ['b1', 'b4'] },
        faseC: { orario: '20:30 - 23:30 Desk info', addettiIds: ['b1'] },
      },
      {
        codice: 'P2',
        nome: 'Buvette alcolica',
        responsabileId: 'b2',
        attiva: true,
        faseA: { orario: '16:30 - 19:30 Allestimento banco, calici, ghiaccio', addettiIds: ['b2'] },
        faseB: { orario: '19:30 - 23:00 Servizio vini e cocktail', addettiIds: ['b2', 'b5'] },
        faseC: { orario: '23:00 - 00:30 Chiusura bar e inscatolamento vetri', addettiIds: ['b2'] },
      },
      {
        codice: 'P3',
        nome: 'Buvette analcolica & Caffetteria',
        responsabileId: 'b2',
        attiva: true,
        faseA: { orario: '16:30 - 19:30 Allestimento dispenser e acque', addettiIds: ['b2'] },
        faseB: { orario: '19:30 - 23:00 Soft drink e caffè espresso', addettiIds: ['b2'] },
        faseC: { orario: '23:00 - 00:30 Pulizia macchina caffè', addettiIds: ['b2'] },
      },
      {
        codice: 'P4',
        nome: 'Runner food / Servizio',
        responsabileId: 'b3',
        attiva: true,
        faseA: { orario: '17:00 - 19:30 Allestimento vassoi e chafing dish', addettiIds: ['b3', 'b4'] },
        faseB: { orario: '19:30 - 22:30 Uscita cibo a vassoio e buffet', addettiIds: ['b3', 'b4', 'b5'] },
        faseC: { orario: '22:30 - 23:30 Servizio dolci e frutta', addettiIds: ['b3', 'b4'] },
      },
      {
        codice: 'P5',
        nome: 'Rimpiazzi e gestione isole',
        responsabileId: 'b3',
        attiva: true,
        faseA: { orario: '17:00 - 19:30 Verifica gel scaldavivande', addettiIds: ['b3'] },
        faseB: { orario: '19:30 - 22:30 Rimpiazzo continuo dalle cucine', addettiIds: ['b3', 'b5'] },
        faseC: { orario: '22:30 - 23:30 Ritiro pirofile e carrelli', addettiIds: ['b3'] },
      },
      {
        codice: 'P6',
        nome: 'Sbarazzo e pulizia',
        responsabileId: 'b6',
        attiva: true,
        faseA: { orario: '17:00 - 19:30 Posizionamento trespoli e mastelli', addettiIds: ['b6'] },
        faseB: { orario: '19:30 - 22:30 Sbarazzo continuo sala e bicchieri', addettiIds: ['b6'] },
        faseC: { orario: '22:30 - 00:45 Sbarazzo massivo sala e differenziata', addettiIds: ['b6', 'b4'] },
      },
      {
        codice: 'P9',
        nome: 'Cucina / Porzionatura (M5)',
        responsabileId: 'b8',
        attiva: true,
        faseA: { orario: '16:00 - 19:30 Accensione forni e linea impiattamento', addettiIds: ['b8'] },
        faseB: { orario: '19:30 - 22:30 Cottura e uscita portate calde', addettiIds: ['b8'] },
        faseC: { orario: '22:30 - 23:30 Pulizia banchi inox e sanificazione', addettiIds: ['b8'] },
      },
    ],
    menu: [
      { id: 'm1', momento: 'Aperitivo / benvenuto', propostaPiatti: 'Prosecco DOCG, Cocktail analcolico, finger food freddi e caldi a passaggio', porzioni: 100, note: 'Passaggio su vassoi' },
      { id: 'm2', momento: 'Antipasto / finger food', propostaPiatti: 'Selezione formaggi DOP con mostarde, salumi artigianali, focacce calde', porzioni: 100, note: 'Isola antipasti' },
      { id: 'm3', momento: 'Primo', propostaPiatti: 'Primo piatto caldo di stagione a passaggio', porzioni: 105, note: 'In cocotte monouso compostabili' },
      { id: 'm4', momento: 'Dolce', propostaPiatti: 'Buffet di piccola pasticceria assortita e frutta fresca', porzioni: 110, note: 'Isola dolci' },
      { id: 'm5', momento: 'Caffè e fine pasto', propostaPiatti: 'Espresso in cialda e amari', porzioni: 100, note: 'Buvette P3' },
    ],
    allergeni: [
      { id: 'al1', ospiteGruppo: 'Ospite da confermare', allergeneDieta: 'Celiachia (Senza Glutine)', gestione: 'Piatto sigillato dedicato con pane confezionato gluten-free', respInSala: 'Mario Rossi' },
    ],
    fabbisogno: [
      { id: 'f1', voce: 'Vino e prosecco', dosePerOspite: 0.5, unitaDose: 'L', formatoAcquisto: 'Bottiglia 0.75 L (Cassa da 6)', note: 'Circa 2-3 calici a persona' },
      { id: 'f2', voce: 'Acqua minerale', dosePerOspite: 0.75, unitaDose: 'L', formatoAcquisto: 'Bottiglia vetro 0.75 L', note: '60% naturale, 40% gassata' },
      { id: 'f3', voce: 'Soft drink e succhi', dosePerOspite: 0.3, unitaDose: 'L', formatoAcquisto: 'Bottiglie 1 L', note: 'Succhi, cola, tonica' },
      { id: 'f4', voce: 'Ghiaccio a cubetti', dosePerOspite: 0.4, unitaDose: 'kg', formatoAcquisto: 'Sacchi 10 kg in polibox termico', note: 'Per cocktail e glacette' },
      { id: 'f5', voce: 'Monouso compostabile', dosePerOspite: 3.5, unitaDose: 'pz', formatoAcquisto: 'Confezioni da 50 pz', note: 'Piattini e forchette' },
    ],
    materiali: [
      { id: 'mat1', n: 1, categoria: 'Bevande', voce: 'Prosecco Superiore DOCG', qta: 36, unitaBaseFormato: 'Bottiglie 0.75 L', tipo: 'M', destinazione: 'P2', contenitore: 'C1', stato: 'P' },
      { id: 'mat2', n: 2, categoria: 'Bevande', voce: 'Acqua minerale (naturale/gassata)', qta: 80, unitaBaseFormato: 'Bottiglie vetro 0.75 L', tipo: 'M', destinazione: 'P3', contenitore: 'C2', stato: 'P' },
      { id: 'mat3', n: 3, categoria: 'Bevande', voce: 'Ghiaccio alimentare a cubetti', qta: 40, unitaBaseFormato: 'kg (4 sacchi da 10kg)', tipo: 'A', destinazione: 'P2', contenitore: 'C3', stato: 'P' },
      { id: 'mat4', n: 4, categoria: 'Vetro e stoviglie', voce: 'Calici vino degustazione', qta: 200, unitaBaseFormato: 'pz (8 ceste da 25)', tipo: 'M', destinazione: 'P2', contenitore: 'C4', stato: 'P' },
      { id: 'mat5', n: 5, categoria: 'Attrezzatura', voce: 'Chafing dish scaldavivande GN 1/1', qta: 4, unitaBaseFormato: 'pz con fornelletti gel', tipo: 'M', destinazione: 'P5', contenitore: 'FC', stato: 'P' },
      { id: 'mat6', n: 6, categoria: 'Pulizia', voce: 'Kit pulizia, trespoli, sacchi neri', qta: 1, unitaBaseFormato: 'kit completo', tipo: 'M', destinazione: 'P6', contenitore: 'C5', stato: 'P' },
    ],
    contenitori: [
      { codice: 'C1', tipo: 'Cassa vini rinforzata', contenutoSintetico: 'Vini e bollicine', destinazione: 'P2', pesoIngombro: '30 kg', checkCaricoBase: false, checkScaricoLocation: false, checkCaricoRitorno: false, checkScaricoBase: false },
      { codice: 'C2', tipo: 'Cassa acque impilabile', contenutoSintetico: 'Acqua minerale naturale e frizzante', destinazione: 'P3', pesoIngombro: '35 kg', checkCaricoBase: false, checkScaricoLocation: false, checkCaricoRitorno: false, checkScaricoBase: false },
      { codice: 'C3', tipo: 'Polibox isotermico', contenutoSintetico: 'Ghiaccio cubetti', destinazione: 'P2', pesoIngombro: '40 kg', checkCaricoBase: false, checkScaricoLocation: false, checkCaricoRitorno: false, checkScaricoBase: false },
      { codice: 'C4', tipo: 'Ceste calici', contenutoSintetico: 'Calici vino e flûte', destinazione: 'P1 e P2', pesoIngombro: '35 kg', checkCaricoBase: false, checkScaricoLocation: false, checkCaricoRitorno: false, checkScaricoBase: false },
      { codice: 'C5', tipo: 'Cassone materiale vario', contenutoSintetico: 'Tovaglie, monouso, kit pulizia', destinazione: 'P4 e P6', pesoIngombro: '25 kg', checkCaricoBase: false, checkScaricoLocation: false, checkCaricoRitorno: false, checkScaricoBase: false },
      { codice: 'FC', tipo: 'Fuori contenitore', contenutoSintetico: 'Chafing dish e dispenser', destinazione: 'P3 e P5', pesoIngombro: 'Colli singoli protetti', checkCaricoBase: false, checkScaricoLocation: false, checkCaricoRitorno: false, checkScaricoBase: false },
    ],
    logistica: [
      { id: 'l1', tipoMovimento: 'Carico alla base', dataOra: `${today} ore 14:00`, chi: 'Squadra magazzino', mezzo: 'Furgone catering', daA: 'Magazzino -> Mezzo', note: 'Caricare ghiaccio per ultimo' },
      { id: 'l2', tipoMovimento: 'Partenza furgone', dataOra: `${today} ore 15:00`, chi: 'Autista', mezzo: 'Furgone catering', daA: 'Base -> Location', giri: '1 giro', note: 'Arrivo previsto entro le 16:15' },
      { id: 'l3', tipoMovimento: 'Rientro alla base', dataOra: `${today} ore 00:45`, chi: 'Autista', mezzo: 'Furgone catering', daA: 'Location -> Base', giri: '1 giro', note: 'Scarico materiale sporco in zona lavaggio' },
    ],
    sicurezza: [
      {
        vieDiFugaUscite: 'Portone principale e uscite di sicurezza con maniglione antipanico',
        cassettaPrimoSoccorso: 'Presente in office cucina e dotazione furgone',
        estintori: 'Estintori a polvere 6kg adiacenti alle uscite',
        referenteSicurezzaLocation: 'Referente Location',
        personaPrimoIntervento: 'Mario Rossi (Capo Servizio certificato)',
        maloreInfortunioProcedura: 'Chiamata immediata 112 NUE; avvisare capo servizio e custode',
        vetroRottoSversamenti: 'Kit scopa/paletta in postazione P6. Vietato raccogliere cocci a mani nude',
        brigataMinorenneAdulto: 'Nessun minore presente nella brigata',
        allegatoPlanimetria: true,
        allegatoSchedaAllergeni: true,
        allegatoMenuDefinitivo: true,
        allegatoPermessiZTL: true,
        allegatoListaOspiti: true,
      },
    ],
    moduloM1: { attivo: false, ospitiAttesi: 100, sistema: 'Talloncini numerati', capacita: '120 posti', responsabileP7: 'Nome addetto', aperturaChiusura: '19:30 - 23:30', oggettiSmarriti: 'Consegna al capo servizio', listaOspitiAccrediti: false, accoglienzaDettagli: 'Accoglienza e guardaroba' },
    moduloM2: { attivo: false, bambiniAttesiFasce: 'Bambini presenti', menuBevandeDedicati: 'Pasta al pomodoro e cotoletta', responsabileP8: 'Animatrice', adultiRiferimentoCommittente: 'Genitori / Committente', attivitaMateriali: 'Tavoli disegno e giochi', zonaSicurezza: 'Lontana da caldi e vetri', orariApertura: '20:00 - 23:00' },
    moduloM3: { attivo: false, tappe: [] },
    moduloM4: {
      attivo: true,
      mezzoTargaAutista: 'Furgone Frigo Catering - Autista di turno',
      squadraCaricoBase: 'Squadra magazzino',
      squadraScaricoLocation: 'Brigata sala e facchinaggio',
      giriAndataOrari: '1 giro ore 15:00',
      giriRitornoOrari: '1 giro ore 00:45',
      percorsoZtlPermessi: 'Permesso transito richiesto',
      accessoMagazzinoBase: 'Chiavi in dotazione',
      caricoCompletatoEntro: '14:50',
      firmaCapoCarico: '',
      firmaRicezione: '',
    },
    moduloM5: {
      attivo: true,
      responsabileCucina: 'Paola Ricci (Chef)',
      porzionaturaChiEDove: 'Banco centrale cucina',
      passaggioCucinaSala: 'Porta office con campanello',
      materialeDestinatoCucinaNote: 'Teglie gastronorm forate e pinze',
      viniAbbinamenti: 'Prosecco per aperitivo, vino rosso per portate calde',
      portate: [
        { id: 'pr1', portata: 'Primo caldo', giri: '2 uscite a vassoio', cosaSiPorta: 'Cocotte calde', chi: 'Runner sala' },
      ],
    },
    moduloM6: { attivo: false, turni: [], oreTotaliVerificate: true, pausaPrevista: true, passaggioConsegneScritto: false },
    chiusura: {
      paxRealiAdulti: 100,
      paxRealiBambini: 0,
      inizioReale: '',
      fineReale: '',
      assenzeSostituzioni: 'Nessuna',
      problemiOrario: 'Nessuno',
      consumi: [
        { id: 'c1', voce: 'Prosecco Superiore DOCG', previsto: 36, consumato: 0, rimastoReso: 0, unita: 'Bottiglie 0.75 L', nota: '' },
        { id: 'c2', voce: 'Acqua minerale', previsto: 80, consumato: 0, rimastoReso: 0, unita: 'Bottiglie 0.75 L', nota: '' },
      ],
      rottureDanni: [],
      noleggiRestituiti: false,
      resiFornitoriFatti: false,
      materialeBaseRientratoContato: false,
      mancanzeSegnalateMagazzino: false,
      cosaHaFunzionato: '',
      cosaCambiareProssimaVolta: '',
      riscontroCommittente: '',
      capoServizioFirma: '',
      dataChiusura: '',
    },
    controlliCapoServizio: [
      { id: 'chk1', testo: 'Brigata confermata: nessuna persona rimasta in stato DC', tipo: 'giorno_prima', completato: false },
      { id: 'chk2', testo: 'Ogni persona assegnata ad almeno una postazione e a una fase', tipo: 'giorno_prima', completato: false },
      { id: 'chk3', testo: 'Ore totali per persona verificate (turni, pause, rispetto contratti)', tipo: 'giorno_prima', completato: false },
      { id: 'chk4', testo: 'Allergeni e diete speciali ricevuti e girati per iscritto a cucina e sala', tipo: 'giorno_prima', completato: false },
      { id: 'chk5', testo: 'Accessi, orari di carico e permessi ZTL confermati con il referente in loco', tipo: 'giorno_prima', completato: false },
      { id: 'chk6', testo: 'Ordini di acquisto e noleggi confermati con orario di consegna in bolla', tipo: 'giorno_prima', completato: false },
      { id: 'chk7', testo: 'Referente in loco incontrato; punti di servizio, quadri e uscite verificate', tipo: 'all_arrivo', completato: false },
      { id: 'chk8', testo: 'Materiale per postazione verificato e assegnato secondo tabella P1-P10', tipo: 'all_arrivo', completato: false },
      { id: 'chk9', testo: 'Divise e igiene personale controllate prima dell’apertura porte', tipo: 'all_arrivo', completato: false },
      { id: 'chk10', testo: 'Briefing finale della brigata svolto con focus allergeni e sicurezza', tipo: 'all_arrivo', completato: false },
      { id: 'chk11', testo: 'Fasi e orari comunicati: chi fa cosa e quando passa da una postazione all’altra', tipo: 'briefing', completato: false },
      { id: 'chk12', testo: 'Postazioni, responsabili e recapiti telefonici distribuiti', tipo: 'briefing', completato: false },
      { id: 'chk13', testo: 'Allergie e diete: piatti, ospiti e chiarito che la brigata NON risponde mai a memoria', tipo: 'briefing', completato: false },
      { id: 'chk14', testo: 'Standard di servizio e tempi di rimpiazzo cucina chiariti', tipo: 'briefing', completato: false },
      { id: 'chk15', testo: 'Imprevisti: chiarito chi decide e chi avvisare tempestivamente', tipo: 'briefing', completato: false },
      { id: 'chk16', testo: 'Chiusura: divieto assoluto di lasciare la postazione senza via libera del Capo Servizio', tipo: 'briefing', completato: false },
      { id: 'chk17', testo: 'Domande e dubbi della brigata chiariti prima del welcome drink', tipo: 'briefing', completato: false },
    ],
    verificheMateriale: [
      { postazioneCod: 'P1', postazioneNome: 'Accoglienza & Welcome', responsabileNome: 'Mario Rossi', materialeCompleto: false, mancanze: '', ok: false },
      { postazioneCod: 'P2', postazioneNome: 'Buvette alcolica', responsabileNome: 'Luigi Bianchi', materialeCompleto: false, mancanze: '', ok: false },
      { postazioneCod: 'P3', postazioneNome: 'Buvette analcolica & Caffetteria', responsabileNome: 'Luigi Bianchi', materialeCompleto: false, mancanze: '', ok: false },
      { postazioneCod: 'P4', postazioneNome: 'Runner food / Servizio', responsabileNome: 'Anna Verdi', materialeCompleto: false, mancanze: '', ok: false },
      { postazioneCod: 'P5', postazioneNome: 'Rimpiazzi e isole', responsabileNome: 'Anna Verdi', materialeCompleto: false, mancanze: '', ok: false },
      { postazioneCod: 'P6', postazioneNome: 'Sbarazzo e pulizia', responsabileNome: 'Davide Romano', materialeCompleto: false, mancanze: '', ok: false },
      { postazioneCod: 'P9', postazioneNome: 'Cucina / Porzionatura', responsabileNome: 'Paola Ricci', materialeCompleto: false, mancanze: '', ok: false },
    ],
    imprevistiLive: [],
    fornitoriNoleggi: [],
    verbaleCarico: {
      mancanzeDanniSegnalati: '',
      caricoBaseFirmaDataOra: '',
      ricezioneLocationFirmaDataOra: '',
      rientroBaseFirmaDataOra: '',
    },
  };
}
